<?php
//random skaicius
$randomas = rand(1111, 9999);
$data = date("Y-m-d");
$val = 0; 
$sk = 0;
$vid = 0;

$klase = ['mokinys1' => ['Klase' => '5B',
                         'Kodas' => $randomas,
                         'Vardas' => 'Melissa',
                         'Pavarde' => 'Lissa',
                         'Pazymiai' => ['Matematika' => 8,
                                        'Informacines Technologijos' => 5, 
                                        'Anglu kalba' => 10],
                         'Data' => $data
         ],
         'mokinys2' => ['Klase' => '5B',
                         'Kodas' => $randomas,
                         'Vardas' => 'Melissa',
                         'Pavarde' => 'Lissa',
                         'Pazymiai' => ['Matematika' => 8,
                                        'Informacines Technologijos' => 5, 
                                        'Anglu kalba' => 10,
                                        'Lenku kalba' => 1],
                         'Data' => $data],
         'mokinys3' => ['Klase' => '5B',
                         'Kodas' => $randomas,
                         'Vardas' => 'Melissa',
                         'Pavarde' => 'Lissa',
                         'Pazymiai' => ['Matematika' => 8,
                                        'Informacines Technologijos' => 5, 
                                        'Anglu kalba' => 10],
                         'Data' => $data],
         'mokinys4' => ['Klase' => '5B',
                         'Kodas' => $randomas,
                         'Vardas' => 'Melissa',
                         'Pavarde' => 'Lissa',
                         'Pazymiai' => ['Matematika' => 8,
                                        'Informacines Technologijos' => 5, 
                                        'Anglu kalba' => 10],
                         'Data' => $data],
         'mokinys5' => ['Klase' => '5B',
                         'Kodas' => $randomas,
                         'Vardas' => 'Melissa',
                         'Pavarde' => 'Lissa',
                         'Pazymiai' => ['Matematika' => 8,
                                        'Informacines Technologijos' => 5, 
                                        'Anglu kalba' => 10],
                         'Data' => $data
         ],
         'mokinys6' => ['Klase' => '5B',
                         'Kodas' => $randomas,
                         'Vardas' => 'Melissa',
                         'Pavarde' => 'Lissa',
                         'Pazymiai' => ['Matematika' => 8,
                                        'Informacines Technologijos' => 5, 
                                        'Anglu kalba' => 10,
                                        'Lenku kalba' => 1],
                         'Data' => $data],
         'mokinys7' => ['Klase' => '5B',
                         'Kodas' => $randomas,
                         'Vardas' => 'Melissa',
                         'Pavarde' => 'Lissa',
                         'Pazymiai' => ['Matematika' => 8,
                                        'Informacines Technologijos' => 5, 
                                        'Anglu kalba' => 10],
                         'Data' => $data],
         'mokinys9' => ['Klase' => '5B',
                         'Kodas' => $randomas,
                         'Vardas' => 'Melissa',
                         'Pavarde' => 'Lissa',
                         'Pazymiai' => ['Matematika' => 8,
                                        'Informacines Technologijos' => 5, 
                                        'Anglu kalba' => 10],
                         'Data' => $data],
                         'mokinys7' => ['Klase' => '5B',
                         'Kodas' => $randomas,
                         'Vardas' => 'Melissa',
                         'Pavarde' => 'Lissa',
                         'Pazymiai' => ['Matematika' => 8,
                                        'Informacines Technologijos' => 5, 
                                        'Anglu kalba' => 10],
                         'Data' => $data],
         'mokinys10' => ['Klase' => '5B',
                         'Kodas' => $randomas,
                         'Vardas' => 'Melissa',
                         'Pavarde' => 'Lissa',
                         'Pazymiai' => ['Matematika' => 7,
                                        'Informacines Technologijos' => 8, 
                                        'Anglu kalba' => 5],
                         'Data' => $data]
        ];